"""documents, chunks with pgvector, knowledge objects

Revision ID: c3c67184ff59
Revises: 40a298643726
Create Date: 2026-08-17 14:56:25.384917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'c3c67184ff59'
down_revision: Union[str, Sequence[str], None] = '40a298643726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('warnings', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('heading_path', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_company_tier', 'document_chunks', ['company_id', 'tier'], unique=False)
    op.create_index(op.f('ix_document_chunks_company_id'), 'document_chunks', ['company_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_tier'), 'document_chunks', ['tier'], unique=False)
    op.create_table('knowledge_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('source_location', sa.Text(), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'verified' OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)", name='ck_verified_requires_verifier'),
    sa.CheckConstraint("status IN ('proposed', 'verified', 'rejected', 'superseded')", name='ck_knowledge_status'),
    sa.CheckConstraint("tier IN ('company', 'industry', 'global')", name='ck_knowledge_tier'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_objects_company_id'), 'knowledge_objects', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_source_document_id'), 'knowledge_objects', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_status'), 'knowledge_objects', ['status'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_tier'), 'knowledge_objects', ['tier'], unique=False)
    op.create_index(op.f('ix_knowledge_objects_type'), 'knowledge_objects', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_objects_type'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_tier'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_status'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_source_document_id'), table_name='knowledge_objects')
    op.drop_index(op.f('ix_knowledge_objects_company_id'), table_name='knowledge_objects')
    op.drop_table('knowledge_objects')
    op.drop_index(op.f('ix_document_chunks_tier'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_company_id'), table_name='document_chunks')
    op.drop_index('ix_chunks_company_tier', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
